[target.riscv64gc-unknown-linux-gnu]
linker = "/home/e0007816/codes/win2030/buildroot/dl/toolchain/bin/riscv64-unknown-linux-gnu-gcc"
ar = "/home/e0007816/codes/win2030/buildroot/dl/toolchain/bin/riscv64-unknown-linux-gnu-ar"
rustflags = [
    "-C", "link-arg=-march=rv64gc",
    "-C", "link-arg=-mabi=lp64d",
    "-C", "link-arg=--sysroot=/home/e0007816/codes/win2030/buildroot/dl/toolchain/sysroot"
]

[env]
CC = "riscv64-unknown-linux-gnu-gcc"
CXX = "riscv64-unknown-linux-gnu-g++"
